# Generated by Django 4.2.1 on 2023-05-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=30)),
                ("Date", models.DateField()),
                ("Priority", models.CharField(max_length=10)),
            ],
        ),
    ]
